# Generated by Django 5.2.6 on 2025-09-17 21:49

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Paciente')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('prontuario', models.CharField(blank=True, max_length=50, null=True, verbose_name='Prontuário')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ProvedorIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Provedor')),
                ('api_url', models.URLField(verbose_name='URL da API')),
                ('api_key', models.CharField(max_length=500, verbose_name='Chave da API')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Provedor de IA',
                'verbose_name_plural': 'Provedores de IA',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PromptIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Prompt')),
                ('prompt_template', models.TextField(verbose_name='Template do Prompt')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('provedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.provedoria', verbose_name='Provedor de IA')),
            ],
            options={
                'verbose_name': 'Prompt de IA',
                'verbose_name_plural': 'Prompts de IA',
                'ordering': ['provedor', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ExameOCT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to=core.models.upload_to_oct, verbose_name='Imagem OCT')),
                ('data_exame', models.DateTimeField(auto_now_add=True, verbose_name='Data do Exame')),
                ('diagnostico_ia', models.TextField(blank=True, null=True, verbose_name='Diagnóstico da IA')),
                ('data_diagnostico', models.DateTimeField(blank=True, null=True, verbose_name='Data do Diagnóstico')),
                ('laudo_pdf', models.FileField(blank=True, null=True, upload_to=core.models.upload_to_laudos, verbose_name='Laudo PDF')),
                ('data_laudo', models.DateTimeField(blank=True, null=True, verbose_name='Data do Laudo')),
                ('status', models.CharField(choices=[('pendente', 'Pendente de Análise'), ('analisando', 'Analisando'), ('concluido', 'Concluído'), ('erro', 'Erro na Análise')], default='pendente', max_length=20, verbose_name='Status')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que realizou o upload')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente', verbose_name='Paciente')),
                ('prompt_usado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.promptia', verbose_name='Prompt Utilizado')),
                ('provedor_ia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.provedoria', verbose_name='Provedor de IA')),
            ],
            options={
                'verbose_name': 'Exame OCT',
                'verbose_name_plural': 'Exames OCT',
                'ordering': ['-data_exame'],
            },
        ),
    ]
